package almacen;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marlene Alejandra Maciel Torres 
 */
import java.awt.Component;
import java.sql.*;
import java.io.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DocumentosDeEntrada extends javax.swing.JFrame {

    /**
     * Creates new form DocumentosDeEntrada1
     */
    
    String año,mes,dia;
    int f,aux,n,uni,verifica,numdoc,maydoc=0;
    float totalf,totalfinal; 
    
    public DocumentosDeEntrada() {
        initComponents();
        
        año = Integer.toString(jCalendarCombo1.getCalendar().get(java.util.Calendar.YEAR));
        mes = Integer.toString(jCalendarCombo1.getCalendar().get(java.util.Calendar.MONTH)+1);
        dia = Integer.toString(jCalendarCombo1.getCalendar().get(java.util.Calendar.DATE));
        jTextField2.setText(dia+" / "+mes+" / "+año);
        
        
        try//Llena el ComboBox1
         {
             Conexion2 miconexion=new Conexion2();//se conecta 
             
             String cons="select * from tablacatalogoconceptos";             
             ResultSet consulta=miconexion.consulta(cons); //se envia la consulta
             
             if(consulta.next())//pegunta si hay datos en la tabla
             {
                 do 
                 {                         
                    jComboBox1.addItem(consulta.getString(2));  //aqui se  inserta los datos en el combobox 
                 }while(consulta.next()); 
             }             
         }         
         catch(Exception ex)
         {
             System.out.print(ex);
         }
        
        
        try//Llena el ComboBox2
         {
             Conexion2 miconexion=new Conexion2();//se conecta 
             
             String cons="select * from tablacatalogoproveedores";             
             ResultSet consulta=miconexion.consulta(cons); //se envia la consulta
             
             if(consulta.next())//pegunta si hay datos en la tabla
             {
                 do 
                 {                         
                    jComboBox2.addItem(consulta.getString(2));  //aqui se  inserta los datos en el combobox 
                 }while(consulta.next()); 
             }             
         }         
         catch(Exception ex)
         {
             System.out.print(ex);
         }
        
        try//Agrega el número del documento
         {
             Conexion2 miconexion=new Conexion2();//se conecta 
             
             String cons="select * from dentradaencabezado";             
             ResultSet consulta=miconexion.consulta(cons); //se envia la consulta
             
             if(consulta.next())//pegunta si hay datos en la tabla
             {
                 do 
                 {  numdoc=Integer.parseInt(consulta.getString(1).toString())+1;                    
                    if(maydoc<numdoc){
                        maydoc=numdoc;
                    }
                    else{
                      maydoc=maydoc;  
                    }
                   jTextField1.setText(Integer.toString(maydoc));//aqui se  inserta el numero del documento
                   
                 }while(consulta.next()); 
             }
             else{
               jTextField1.setText(Integer.toString(1));  
             }
         }         
         catch(Exception ex)
         {
             System.out.print(ex);
         }
        f=0;        
        n=1;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        totalmov = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        nmovimiento = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        unidad = new javax.swing.JTextField();
        clave = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jFrame1.setMinimumSize(new java.awt.Dimension(612, 449));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame1WindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        totalmov.setBackground(new java.awt.Color(255, 204, 255));
        totalmov.setEditable(false);
        totalmov.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalmov.setText("0.0");
        totalmov.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        totalmov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalmovMouseClicked(evt);
            }
        });
        totalmov.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                totalmovComponentShown(evt);
            }
        });
        totalmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalmovActionPerformed(evt);
            }
        });
        totalmov.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                totalmovAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Guardar Movimiento");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        nmovimiento.setBackground(new java.awt.Color(255, 204, 255));
        nmovimiento.setEditable(false);

        precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precio.setText("0.0");
        precio.setToolTipText("");
        precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total del Movimiento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Número de Movimiento: ");

        unidad.setBackground(new java.awt.Color(255, 204, 255));
        unidad.setEditable(false);

        clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                claveMouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Precio:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Descripción: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Clave del Producto: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cantidad:");

        descripcion.setBackground(new java.awt.Color(255, 204, 255));
        descripcion.setEditable(false);
        descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descripcionMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Captura de Movimientos de Entrada");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Unidad:");

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Cancelar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        cantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cantidad.setText("0");
        cantidad.setToolTipText("");
        cantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cantidadMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Modifica el movimiento");

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Guardar Movimiento Modificado");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalmov, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel12))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(jLabel14))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10)
                                    .addComponent(jButton13))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalmov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton10))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setMinimumSize(new java.awt.Dimension(770, 598));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        No.", "     Clave", "   Descripción", "    Unidad", "   Cantidad", "    Precio", "   Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Total: ");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("0.0");

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Guardar documento y Sus movimientos");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cancelar Documento");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Modificar Movimiento");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Borrar Movimiento");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton3)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(93, 93, 93))
        );

        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encabezado del Documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setText("Número del Documento: ");

        jLabel2.setText("Fecha: ");

        jCalendarCombo1.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                jCalendarCombo1jCalendarCombo1DateChanged(evt);
            }
        });
        jCalendarCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalendarCombo1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Concepto:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Agregar Nuevo Concepto");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Proveedor: ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno" }));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Agregar Nuevo Proveedor");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2jButton2ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Agregar Movimiento");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Cancelar Movimientos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addGap(20, 20, 20)
                                        .addComponent(jButton8))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jCalendarCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /*
     * Código para sacar el número de fila seleccionado
     */
    private int numFila(){
        int fila;
        fila=jTable1.getSelectedRow();
        return fila;
    }
    
    private void jFrame1WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1WindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFrame1WindowActivated

    private void totalmovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalmovMouseClicked
        // TODO add your handling code here: 
       if (cantidad.getText().equals("")&&precio.getText().equals("")||cantidad.getText().equals("")||precio.getText().equals("")){
            
        }
        else{
            float prec, total;
            int cant;
            if (cantidad.getText() != null && precio.getText() != null) {
                cant = Integer.parseInt(cantidad.getText().toString());
                prec = Float.parseFloat(precio.getText().toString());
            total = cant * prec;
            totalmov.setText(Float.toString(total));
            }
        }
    }//GEN-LAST:event_totalmovMouseClicked

    private void totalmovComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_totalmovComponentShown
        // TODO add your handling code here:

   }//GEN-LAST:event_totalmovComponentShown

    private void totalmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalmovActionPerformed
        // TODO add your handling code here: 
              
    }//GEN-LAST:event_totalmovActionPerformed

    private void totalmovAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_totalmovAncestorAdded
        // TODO add your handling code here:        
    }//GEN-LAST:event_totalmovAncestorAdded

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        n=n+1;
       if(nmovimiento.getText().equals("")||clave.getText().equals("")||
           descripcion.getText().equals("")||unidad.getText().equals("")||cantidad.getText().equals("0")||
           precio.getText().equals("0.0")||totalmov.getText().equals("0.0")){
             JOptionPane.showMessageDialog(null," Faltan datos ");           
        }
        
       else{
        float pre,total;
        pre=Float.parseFloat(precio.getText().toString());
        total=Float.parseFloat(totalmov.getText().toString());
        jFrame1.setVisible(false); 
        
        //Lo que cambia es la fila jTable.setValueAt( dato ,fila ,columna );
        while(jTable1.getValueAt(f,0)!=null){
            f++;
        }
        jTable1.setValueAt(nmovimiento.getText().toString(),f,0); 
        jTable1.setValueAt(clave.getText().toString(),f,1);
        jTable1.setValueAt(descripcion.getText().toString(),f,2);
        jTable1.setValueAt(unidad.getText().toString(),f,3);
        jTable1.setValueAt(cantidad.getText().toString(),f,4);
        jTable1.setValueAt(pre,f,5);
        jTable1.setValueAt(total,f,6);
           
        nmovimiento.setText("");
        clave.setText("");
        descripcion.setText("");
        unidad.setText("");
        cantidad.setText("0");
        precio.setText("0.0");
        totalmov.setText("0.0");
        
        JOptionPane.showMessageDialog(null,"Movimiento Guardado"); 
        totalFinal();        
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void precioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioMouseClicked
        // TODO add your handling code here:
        precio.setText("");
    }//GEN-LAST:event_precioMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        nmovimiento.setText("");
        clave.setText("");
        descripcion.setText("");
        unidad.setText("");
        cantidad.setText("0");
        precio.setText("0.0");
        totalmov.setText("0.0");
        DefaultTableModel elimina=(DefaultTableModel) jTable1.getModel(); 
        elimina.removeRow(numFilas()-1); 
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void agregarFila(){
        int filas=0;
        DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
        modelo.addRow(new Object[filas]);
        filas++;
    }
    
    private void agregarmovimientos(){
        aux=0;
        while(aux<=numFilas()-1){
        try{
            //Variable para conexion
            Conexion miConexion;
            miConexion = new Conexion();
            //Declarar cadena para sentencias SQL 
            String SentenciaInsert="insert into dentradamovimientos value (?,?,?,?,?,?,?,?)"; 
            //Preparar sentencia SQL
            miConexion.psPrepararSentencias=miConexion.conn.prepareStatement(SentenciaInsert);
            //Ingresar datos de las cajas de texto
            miConexion.psPrepararSentencias.setString(1,jTable1.getValueAt(aux,0).toString());
            miConexion.psPrepararSentencias.setString(2,jTable1.getValueAt(aux,1).toString());
            miConexion.psPrepararSentencias.setString(3,jTable1.getValueAt(aux,2).toString());
            miConexion.psPrepararSentencias.setString(4,jTable1.getValueAt(aux,3).toString());
            miConexion.psPrepararSentencias.setString(5,jTable1.getValueAt(aux,4).toString());
            miConexion.psPrepararSentencias.setString(6,jTable1.getValueAt(aux,5).toString());
            miConexion.psPrepararSentencias.setString(7,jTable1.getValueAt(aux,6).toString());
            miConexion.psPrepararSentencias.setString(8,jTextField1.getText());
            //Escribir en la tabla
            miConexion.psPrepararSentencias.executeUpdate();
            aux=aux+1;
            //JOptionPane.showMessageDialog(null," Datos Guardados Correctamente");
            
        }catch(Exception e){
            System.out.println(e.getCause());
        } 
        }
    }
    private void cantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadMouseClicked
        // TODO add your handling code here:
        cantidad.setText("");
    }//GEN-LAST:event_cantidadMouseClicked

    private void descripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descripcionMouseClicked
        // TODO add your handling code here:
        if(clave.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Proporcione la clave del producto");
        }
        else{
           int c;
        verifica=0;
        uni=0;
        c=Integer.parseInt(clave.getText().toString());        
         
         try// Método para mostrar la descripcion del producto
         {
             Conexion2 miconexion=new Conexion2();//se conecta 
             
             String cons="select *from tablacatalogoproductos";             
             ResultSet consulta=miconexion.consulta(cons); //se envia la consulta
             
             if(consulta.next())//pegunta si hay datos en la tabla
             {
                    do{ 
                        if(c==Integer.parseInt(consulta.getString(1))){
                          descripcion.setText(consulta.getString(2));
                          uni=Integer.parseInt(consulta.getString(3));
                          verifica=1;
                        };
                  }while(consulta.next());
                 if(verifica!=1){
                     JOptionPane.showMessageDialog(null,"La clave del producto es incorrecta");
                     clave.setText(""); 
                     descripcion.setText("");
                     unidad.setText("");
                     cantidad.setText("0");
                     precio.setText("0.0");
                     totalmov.setText("0.0");                    
                 }
             }
             
             
         }         
         catch(Exception ex)
         {
             System.out.print(ex);
         }
         
         try// Método para mostrar la unidad del producto
         {
             Conexion2 miconexion=new Conexion2();//se conecta 
             
             String cons="select *from tablacatalogounidades";             
             ResultSet consulta=miconexion.consulta(cons); //se envia la consulta
             
             if(consulta.next())//pegunta si hay datos en la tabla
             {
                    do{ 
                        if(uni==Integer.parseInt(consulta.getString(1))){
                          unidad.setText(consulta.getString(2));                          
                        }
                  }while(consulta.next());
             }       
             
         }         
         catch(Exception ex)
         {
             System.out.print(ex);
         } 
        }
    }//GEN-LAST:event_descripcionMouseClicked

    private void claveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveMouseEntered
        // TODO add your handling code here:      
    }//GEN-LAST:event_claveMouseEntered

    private void claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveMouseClicked
        // TODO add your handling code here:
        clave.setText("");
        descripcion.setText("");
        unidad.setText("");
        cantidad.setText("0");
        precio.setText("0.0");
        totalmov.setText("0.0");         
    }//GEN-LAST:event_claveMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        float pre,total;
        pre=Float.parseFloat(precio.getText().toString());
        total=Float.parseFloat(totalmov.getText().toString());
        
        jTable1.setValueAt(nmovimiento.getText().toString(),numFila(),0); 
        jTable1.setValueAt(clave.getText().toString(),numFila(),1);
        jTable1.setValueAt(descripcion.getText().toString(),numFila(),2);
        jTable1.setValueAt(unidad.getText().toString(),numFila(),3);
        jTable1.setValueAt(cantidad.getText().toString(),numFila(),4);
        jTable1.setValueAt(pre,numFila(),5);
        jTable1.setValueAt(total,numFila(),6);
           
        nmovimiento.setText("");
        clave.setText("");
        descripcion.setText("");
        unidad.setText("");
        cantidad.setText("0");
        precio.setText("0.0");
        totalmov.setText("0.0");
      
        totalFinal();
        JOptionPane.showMessageDialog(null,"Movimiento Modificado"); 
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    /*
     * Código para sacar el numro de filas del jTable1
     */
    private int numFilas(){
        int filas;
        filas=jTable1.getRowCount();
        return filas;
    }
    
    /*
     * Código para sacar el total final de todos los movimientos
     */
    private void totalFinal(){
        System.out.println(numFilas());
        totalf=0;
        aux=0;
        while(aux<=numFilas()-1){
            totalfinal=Float.parseFloat(jTable1.getValueAt(aux,6).toString());
            totalf=totalf+totalfinal;
            aux=aux+1;
        }
        jTextField3.setText(Float.toString(totalf));
    }
    /*
     * Código para sacar el número de fila seleccionado
     */
    
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        nmovimiento.setText("");
        clave.setText("");
        descripcion.setText("");
        unidad.setText("");
        cantidad.setText("0");
        precio.setText("0.0");
        totalmov.setText("0.0");
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jLabel14.setVisible(false);
        jLabel12.setVisible(true);

        jButton12.setVisible(false);
        jButton7.setVisible(true);

        jButton10.setVisible(true);
        jButton13.setVisible(false);
        if (jTextField1.getText().equals("") || jComboBox1.getSelectedIndex() == 0 || jComboBox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Complete la información requerida antes de continuar ");
        } else {
            jFrame1.setVisible(true);
            jPanel2.setVisible(true);
            
            jButton8.setVisible(false);
            //new CapturaMovimientosDeEntrada().setVisible(true);

            Component[] componentes = jPanel1.getComponents();
            for (int cont = 0; cont < componentes.length; cont++) {
                componentes[cont].setEnabled(false);
            }
            jButton11.setEnabled(true);
            agregarFila();
            String num;
            num = Integer.toString(numFilas());
            nmovimiento.setText(num);
        }
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2jButton2ActionPerformed
        // TODO add your handling code here:
        new catalogoProveedores().setVisible(true);
    }//GEN-LAST:event_jButton2jButton2ActionPerformed

    private void jButton1jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1jButton1ActionPerformed
        // TODO add your handling code here:
        new catalogoConceptos().setVisible(true);
    }//GEN-LAST:event_jButton1jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:

   }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCalendarCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalendarCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCalendarCombo1ActionPerformed

    private void jCalendarCombo1jCalendarCombo1DateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_jCalendarCombo1jCalendarCombo1DateChanged
        // TODO add your handling code here:
        año = Integer.toString(jCalendarCombo1.getCalendar().get(java.util.Calendar.YEAR));
        mes = Integer.toString(jCalendarCombo1.getCalendar().get(java.util.Calendar.MONTH) + 1);
        dia = Integer.toString(jCalendarCombo1.getCalendar().get(java.util.Calendar.DATE));

        jTextField2.setText(dia + " / " + mes + " / " + año);
    }//GEN-LAST:event_jCalendarCombo1jCalendarCombo1DateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.out.println(numFila());
        if (numFila() >= 0) {
            DefaultTableModel elimina = (DefaultTableModel) jTable1.getModel();
            elimina.removeRow(numFila());
            totalFinal();
            aux = 0;
            while (aux <= numFilas() - 1) {
                jTable1.setValueAt(aux + 1, aux, 0);
                aux = aux + 1;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila de la Tabla para Eliminar");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.out.println(numFila());
        if (numFila() >= 0) {

            jLabel14.setVisible(true);
            jLabel12.setVisible(false);

            jButton12.setVisible(true);
            jButton7.setVisible(false);

            jButton10.setVisible(false);
            jButton13.setVisible(true);

            nmovimiento.setText(jTable1.getValueAt(numFila(), 0).toString());
            clave.setText(jTable1.getValueAt(numFila(), 1).toString());
            descripcion.setText(jTable1.getValueAt(numFila(), 2).toString());
            unidad.setText(jTable1.getValueAt(numFila(), 3).toString());
            cantidad.setText(jTable1.getValueAt(numFila(), 4).toString());
            precio.setText(jTable1.getValueAt(numFila(), 5).toString());
            totalmov.setText(jTable1.getValueAt(numFila(), 6).toString());
            jFrame1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila de la Tabla para Modificar");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {//Borra los datos del jTable de los movimientos
            //Variable para conexion
            Conexion miConexion;
            miConexion = new Conexion();
            //Declarar cadena para sentencias SQL 
            String SentenciaInsert = "delete from dentradamovimientos where NumDeDocumento=(?)";
            //Preparar sentencia SQL
            miConexion.psPrepararSentencias = miConexion.conn.prepareStatement(SentenciaInsert);
            //Ingresar datos de las cajas de texto
            miConexion.psPrepararSentencias.setString(1, jTextField1.getText());

            //Escribir en la tabla
            miConexion.psPrepararSentencias.executeUpdate();

        } catch (Exception e) {
            System.out.println(e.getCause());
        }

        try { //Borra los datos del encabezado del documento
            //Variable para conexion
            Conexion miConexion;
            miConexion = new Conexion();
            //Declarar cadena para sentencias SQL 
            String SentenciaInsert = "delete from dentradaencabezado where NumeroDeDocumento=(?)";
            //Preparar sentencia SQL
            miConexion.psPrepararSentencias = miConexion.conn.prepareStatement(SentenciaInsert);
            //Ingresar datos de las cajas de texto
            miConexion.psPrepararSentencias.setString(1, jTextField1.getText());

            //Escribir en la tabla
            miConexion.psPrepararSentencias.executeUpdate();

            JOptionPane.showMessageDialog(null, "Documento Cancelado");
        } catch (Exception e) {
            System.out.println(e.getCause());
        }
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {//Guarda el encabezado del documento
            //Variable para conexion
            Conexion miConexion;
            miConexion = new Conexion();
            //Declarar cadena para sentencias SQL 
            String SentenciaInsert = "insert into dentradaencabezado value (?,?,?,?)";
            //Preparar sentencia SQL
            miConexion.psPrepararSentencias = miConexion.conn.prepareStatement(SentenciaInsert);
            //Ingresar datos de las cajas de texto
            miConexion.psPrepararSentencias.setString(1, jTextField1.getText());
            miConexion.psPrepararSentencias.setString(2, jTextField2.getText());
            miConexion.psPrepararSentencias.setString(3, jComboBox1.getSelectedItem().toString());
            miConexion.psPrepararSentencias.setString(4, jComboBox2.getSelectedItem().toString());
            //Escribir en la tabla
            miConexion.psPrepararSentencias.executeUpdate();

            //JOptionPane.showMessageDialog(null," Datos Guardados Correctamente");
        } catch (Exception e) {
            System.out.println(e.getCause());
        }

        try {//Guarda el total del documento
            //Variable para conexion
            Conexion miConexion;
            miConexion = new Conexion();
            //Declarar cadena para sentencias SQL 
            String SentenciaInsert = "insert into dentradatotal value (?,?)";
            //Preparar sentencia SQL
            miConexion.psPrepararSentencias = miConexion.conn.prepareStatement(SentenciaInsert);
            //Ingresar datos de las cajas de texto
            miConexion.psPrepararSentencias.setString(1, jTextField1.getText());
            miConexion.psPrepararSentencias.setString(2, jTextField3.getText());
            //Escribir en la tabla
            miConexion.psPrepararSentencias.executeUpdate();

            JOptionPane.showMessageDialog(null, " Datos Guardados Correctamente");
        } catch (Exception e) {
            System.out.println(e.getCause());
        }
        agregarmovimientos();//Guarda los movimientos
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentosDeEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentosDeEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentosDeEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentosDeEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DocumentosDeEntrada().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField clave;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nmovimiento;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField totalmov;
    private javax.swing.JTextField unidad;
    // End of variables declaration//GEN-END:variables

    private void addRow(Object[] nuevo) {
        throw new UnsupportedOperationException("Not yet implemented");
    } 
}
